# permissions for end users to edit handpays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: handpay-editor-role
rules:
- apiGroups:
  - apps.zenghao.com
  resources:
  - handpays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.zenghao.com
  resources:
  - handpays/status
  verbs:
  - get
